// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7-ixgtpX6iJxMSQBlZaCK5vE6oMMc0rs',
    appId: '1:1091300834366:android:c3523e32f7857835e1256f',
    messagingSenderId: '1091300834366',
    projectId: 'paycircle-c8ed2',
    authDomain: 'paycircle-c8ed2.firebaseapp.com',
    storageBucket: 'paycircle-c8ed2.firebasestorage.app',
    measurementId: 'G-XFQ6XPVXHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoDlyhBhdTRvlVA6yTTvONm2ZJJmGd7m8',
    appId: '1:1091300834366:android:c3523e32f7857835e1256f',
    messagingSenderId: '1091300834366',
    projectId: 'paycircle-c8ed2',
    storageBucket: 'paycircle-c8ed2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLw2S0yJSou6-Y5SWXEylv7M2Ru_frOwo',
    appId: '1:1091300834366:android:c3523e32f7857835e1256f',
    messagingSenderId: '1091300834366',
    projectId: 'paycircle-c8ed2',
    storageBucket: 'paycircle-c8ed2.firebasestorage.app',
    iosBundleId: 'com.example.payCircle',
  );
}
